#!/usr/bin/env bash
# bash script to install nginx web server & make the following configurations:

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Holberton School" > /var/www/html/index.html'
sudo systemctl start nginx.service